#!/bin/bash

# 颜色定义
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}"
echo "========================================"
echo "    个人知识库系统 - 免费部署指南"
echo "========================================"
echo -e "${NC}"
echo ""

# 显示部署清单
echo -e "${BLUE}【部署清单】${NC}"
echo ""
echo "1. 📊 数据库：PlanetScale (免费)"
echo "   - 10GB 存储"
echo "   - 50亿行读取/月"
echo "   - 区域：推荐选亚太"
echo ""

echo "2. 🚀 后端：Railway (免费 $5/月)"
echo "   - 自动部署"
echo "   - 内网数据库连接"
echo "   - 日志监控"
echo ""

echo "3. 🎨 前端：Vercel (免费)"
echo "   - 100GB 带宽/月"
echo "   - 全球 CDN"
echo "   - 自动 HTTPS"
echo ""

echo -e "${YELLOW}【部署步骤】${NC}"
echo ""

echo -e "${GREEN}步骤 1: 准备数据库 (PlanetScale)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. 访问: https://planetscale.com/"
echo "2. 使用 GitHub 账号登录"
echo "3. 点击 'New database'"
echo "4. 填写信息:"
echo "   - Database name: knowledge_db"
echo "   - Region: 推荐选择 AWS ap-southeast-1 (新加坡)"
echo "5. 点击 'Create database'"
echo "6. 创建完成后，点击数据库 → 'Connect'"
echo "7. 选择 '@ PlanetScale Connect' (或 'Prisma')"
echo "8. 复制连接字符串，格式类似:"
echo "   mysql+aiomysql://xxx:xxx@aws.connect.psdb.cloud/knowledge_db"
echo ""

echo -e "${GREEN}步骤 2: 部署后端 (Railway)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. 访问: https://railway.app/"
echo "2. 使用 GitHub 账号登录"
echo "3. 点击 'New Project'"
echo "4. 点击 'Deploy from GitHub repo'"
echo "5. 授权您的 GitHub 账号"
echo "6. 选择此项目仓库"
echo "7. 点击 'Add Variables' 配置环境变量:"
echo -e "${YELLOW}   DATABASE_URL${NC} = <粘贴 PlanetScale 连接字符串>"
echo -e "${YELLOW}   SECRET_KEY${NC} = <访问 https://randomkeygen.com/ 生成随机密钥>"
echo -e "${YELLOW}   CORS_ORIGINS${NC} = [\"https://your-frontend.vercel.app\"]"
echo -e "${YELLOW}   DEBUG${NC} = False"
echo "8. 点击 'Deploy' 开始部署"
echo "9. 等待部署完成（约2-3分钟）"
echo "10. 获取后端 URL，格式: https://xxx.up.railway.app"
echo ""

echo -e "${GREEN}步骤 3: 部署前端 (Vercel)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. 访问: https://vercel.com/"
echo "2. 使用 GitHub 账号登录"
echo "3. 点击 'Add New Project'"
echo "4. 点击 'Import Git Repository'"
echo "5. 输入仓库地址或从列表选择"
echo "6. 配置项目:"
echo -e "   ${YELLOW}Project Name${NC}: personal-knowledge"
echo -e "   ${YELLOW}Framework Preset${NC}: Vite"
echo -e "   ${YELLOW}Root Directory${NC}: frontend"
echo -e "   ${YELLOW}Build Command${NC}: npm run build"
echo -e "   ${YELLOW}Output Directory${NC}: dist"
echo "   ${YELLOW}Install Command${NC}: npm install"
echo "7. 点击 'Add Environment Variable':"
echo -e "   ${YELLOW}VITE_API_URL${NC} = https://your-backend.up.railway.app"
echo "8. 点击 'Deploy'"
echo "9. 等待部署完成"
echo "10. 获取前端 URL: https://your-frontend.vercel.app"
echo ""

echo -e "${GREEN}步骤 4: 执行数据库迁移${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. 打开 Railway 项目"
echo "2. 点击 backend service"
echo "3. 打开 'Console' 标签"
echo "4. 执行命令:"
echo "   python scripts/migrate_production.py"
echo "5. 看到 '数据库迁移完成' 即成功"
echo ""

echo -e "${GREEN}步骤 5: 配置 CI/CD 自动化${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. 获取 Railway Token:"
echo "   - Railway → Account → API Tokens"
echo "   - 点击 'New Token'"
echo "   - 权限选择: Read-Only 即可"
echo "   - 复制 Token"
echo ""
echo "2. 获取 Railway Project ID:"
echo "   - Railway 项目页面查看 URL"
echo "   - 格式: xxx-xxxxx (在项目 URL 中)"
echo ""
echo "3. 获取 Vercel Token:"
echo "   - Vercel → Settings → Tokens"
echo "   - 点击 'Create'"
echo "   - Scope: Full Account"
echo "   - 复制 Token"
echo ""
echo "4. 配置 GitHub Secrets:"
echo "   - 进入 GitHub 仓库"
echo "   - Settings → Secrets and variables → Actions"
echo "   - 点击 'New repository secret' 添加以下 secrets:"
echo -e "   ${YELLOW}RAILWAY_TOKEN${NC}"
echo -e "   ${YELLOW}RAILWAY_PROJECT_ID${NC}"
echo -e "   ${YELLOW}VERCEL_TOKEN${NC}"
echo ""
echo "5. 配置完成后，每次 push 到 main 分支将自动部署！"
echo ""

echo -e "${GREEN}步骤 6: 更新前端配置${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. 将后端 URL 更新到 frontend/.env.production:"
echo "   VITE_API_URL=https://your-backend.up.railway.app"
echo ""
echo "2. 将后端 URL 更新到 frontend/vercel.json"
echo "3. 提交并推送代码:"
echo "   git add ."
echo "   git commit -m 'chore: update production config'"
echo "   git push origin main"
echo "4. 等待自动部署完成"
echo ""

echo -e "${GREEN}步骤 7: 验证部署${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. 访问前端 URL 测试"
echo "2. 尝试注册/登录功能"
echo "3. 创建笔记测试"
echo "4. 检查上传头像功能"
echo "5. 查看后端日志确认无错误"
echo ""

echo -e "${BLUE}【故障排查】${NC}"
echo ""
echo "❌ CORS 错误:"
echo "   检查 Railway 环境变量 CORS_ORIGINS 是否包含前端域名"
echo ""
echo "❌ 数据库连接失败:"
echo "   检查 DATABASE_URL 格式是否正确"
echo "   确保是 mysql+aiomysql:// 开头"
echo ""
echo "❌ 前端无法访问后端:"
echo "   检查 Vercel 环境变量 VITE_API_URL"
echo "   确保后端 Railway service 正在运行"
echo ""

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  配置完成！祝您部署顺利！${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
